let dataObjects = {
  saldo: 0,
  transactions: [
    // {
    //   id: 576893,
    //   date: "2023-07-26",
    //   type: false,
    //   category: "Main expenses",
    //   comment: "Bought groceries",
    //   sum: 150,
    // },
    // {
    //   id: 724613,
    //   date: "2023-07-27",
    //   type: true,
    //   category: "Car",
    //   comment: "Filled up gas tank",
    //   sum: 500,
    // },
    // {
    //   id: 982314,
    //   date: "2023-07-28",
    //   type: true,
    //   category: "Main expenses",
    //   comment: "Paid electricity bill",
    //   sum: 300,
    // },
    // {
    //   id: 732198,
    //   date: "2023-07-29",
    //   type: false,
    //   category: "Self care",
    //   comment: "Bought new skincare products",
    //   sum: 400,
    // },
    // {
    //   id: 541936,
    //   date: "2023-07-30",
    //   type: true,
    //   category: "Products",
    //   comment: "Ordered new shoes online",
    //   sum: 350,
    // },
    // {
    //   id: 103785,
    //   date: "2023-07-31",
    //   type: false,
    //   category: "Main expenses",
    //   comment: "Dinner with friends",
    //   sum: 100,
    // },
    // {
    //   id: 203498,
    //   date: "2023-08-01",
    //   type: true,
    //   category: "Car",
    //   comment: "Car maintenance",
    //   sum: 600,
    // },
    // {
    //   id: 428935,
    //   date: "2023-08-02",
    //   type: false,
    //   category: "Household products",
    //   comment: "Bought cleaning supplies",
    //   sum: 200,
    // },
    // {
    //   id: 315287,
    //   date: "2023-08-03",
    //   type: true,
    //   category: "Main expenses",
    //   comment: "Paid rent",
    //   sum: 450,
    // },
    // {
    //   id: 890643,
    //   date: "2023-08-04",
    //   type: false,
    //   category: "Child care",
    //   comment: "Bought new toys for kids",
    //   sum: 50,
    // },
  ],
};

export default dataObjects;
